FROM quay.io/konflux-ci/buildah-task:latest@sha256:4d8273444b0f2781264c232e12e88449bbf078c99e3da2a7f6dcaaf27bc53712

WORKDIR /scripts

COPY scripts/inject-icm.sh /scripts

LABEL \
  description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  io.k8s.description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  summary="Inject an ICM (image content manifest) file" \
  io.k8s.display-name="Inject an ICM (image content manifest) file" \
  name="Inject an ICM (image content manifest) file" \
  com.redhat.component="inject-icm"

ENTRYPOINT ["/scripts/inject-icm.sh"]

