FROM quay.io/konflux-ci/buildah-task:latest@sha256:abbe85cd9fea181eaf38aa53ec51277ea927af97aeac7703a729f744c8623460

WORKDIR /scripts

COPY scripts/inject-icm.sh /scripts

LABEL \
  description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  io.k8s.description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  summary="Inject an ICM (image content manifest) file" \
  io.k8s.display-name="Inject an ICM (image content manifest) file" \
  name="Inject an ICM (image content manifest) file" \
  com.redhat.component="inject-icm"

ENTRYPOINT ["/scripts/inject-icm.sh"]

