apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-test
spec:
  description: >-
    This task can be used to run e2e tests
  params:
    - name: e2e_test_namespace
      type: string
    - name: app_suffix
      type: string
    - name: ec_pipelines_repo_url
      type: string
    - name: ec_pipelines_repo_revision
      type: string
    - name: custom_build_bundle
      type: string
  steps:
    - name: e2e-test
      image: quay.io/redhat-user-workloads/konflux-qe-team-tenant/konflux-e2e/konflux-e2e-tests:2c04894d1123db0b82d899b58fa762d143753d57
      command: ["/konflux-e2e/konflux-e2e.test"]
      args: [
        "--ginkgo.label-filter=source-build-e2e",
        "--ginkgo.no-color",
        "--ginkgo.v",
        "--ginkgo.timeout=2h"
      ]
      securityContext:
        capabilities:
          add:
          - SETFCAP
      env:
      - name: APP_SUFFIX
        value: "$(params.app_suffix)"
      - name: COMPONENT_REPO_URLS
        value: "https://github.com/konflux-qe-bd/source-build-parent-image-with-digest-only"
      - name: QUAY_E2E_ORGANIZATION
        value: redhat-appstudio-qe
      - name: E2E_APPLICATIONS_NAMESPACE
        value: "$(params.e2e_test_namespace)"
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: e2e-tests-github-token
            key: password
      - name: MY_GITHUB_ORG
        value: konflux-qe-bd
      - name: EC_PIPELINES_REPO_URL
        value: $(params.ec_pipelines_repo_url)
      - name: EC_PIPELINES_REPO_REVISION
        value: $(params.ec_pipelines_repo_revision)
      - name: CUSTOM_BUILD_PIPELINE_BUNDLE
        value: $(params.custom_build_bundle)
