name: Build Multi Platform Runner image

on:
  push:
    branches:
      - main
    paths:
      - multi-platform-runner/Dockerfile

  pull_request:
    branches:
      - main
    paths:
      - multi-platform-runner/Dockerfile


env:
  REGISTRY: quay.io/redhat-appstudio
  IMAGE_NAME: multi-platform-runner

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@3a51aade9afa17e5c78256bcbe2e1ee08c7b995b # v3.0.2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }}
        context: .
        containerfiles: |
            ./multi-platform-runner/Dockerfile

    - name: Push to Quay
      if: github.event_name == 'push'  # don't push image from PR
      uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
