name: Source container build

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/source-build.yaml
    - source-container-build/**

  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/source-build.yaml
    - source-container-build/**

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0
      with:
        python-version: '3.14'
    - name: Run checks
      run: |
        python3 -m pip install tox
        cd ./source-container-build/app/
        tox
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
      with:
        dockerfile: ./source-container-build/Dockerfile
